#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# Rosie Atelier — production launcher (VPS · VM · Docker · bare metal)
#
#   ./scripts/start-prod.sh          # build if needed, then serve on :3000
#   PORT=8080 ./scripts/start-prod.sh
#   HOST=127.0.0.1 ./scripts/start-prod.sh   # behind a reverse proxy
#
# It is idempotent: dependencies are installed only when missing, the Next.js
# build is produced only when absent, and a missing .env.local is generated with
# strong random secrets so the admin panel is never accidentally unprotected.
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

cd "$(dirname "$0")/.."

PORT="${PORT:-3000}"
HOST="${HOST:-0.0.0.0}"
ENV_FILE=".env.local"

log() { printf '\033[1;36m▸ %s\033[0m\n' "$*"; }

# ── 1. environment ───────────────────────────────────────────────────────────
if [[ ! -f "$ENV_FILE" ]]; then
  log "no $ENV_FILE — generating one with fresh credentials"
  ADMIN_PASS="Rosie!$(openssl rand -base64 12 | tr -d '/+=' | cut -c1-14)"
  cat > "$ENV_FILE" <<EOF
# Generated by scripts/start-prod.sh — keep this file secret, never commit it.
ADMIN_EMAIL=admin@rosie-atelier.local
ADMIN_PASSWORD=${ADMIN_PASS}
OWNER_EMAIL=owner@rosie-atelier.local
AUTH_SECRET=$(openssl rand -hex 32)

# Content persistence: leave empty to use ./data/content.json (file backend).
# Set both to share content across serverless instances (Upstash Redis).
UPSTASH_REDIS_REST_URL=
UPSTASH_REDIS_REST_TOKEN=

# Canonical URL used by sitemap.xml / robots.txt / OG tags.
NEXT_PUBLIC_SITE_URL=http://localhost:${PORT}
EOF
  chmod 600 "$ENV_FILE"
  log "credentials written to $ENV_FILE — open it to read ADMIN_PASSWORD"
fi

# ── 2. dependencies ──────────────────────────────────────────────────────────
if [[ ! -d node_modules ]]; then
  log "installing dependencies (npm ci)"
  npm ci --no-audit --no-fund
fi

# ── 3. build ─────────────────────────────────────────────────────────────────
if [[ ! -f .next/BUILD_ID ]]; then
  log "building for production (npm run build)"
  npm run build
fi

# ── 4. persistent content directory ──────────────────────────────────────────
mkdir -p data

# ── 5. serve ─────────────────────────────────────────────────────────────────
log "starting Next.js on http://${HOST}:${PORT}  (health: /api/health)"
exec npx next start -H "$HOST" -p "$PORT"
